In [46]:
import pandas as pd
import numpy as np
import seaborn as sns
hotpot = pd.read_csv("hotpot.csv")
hotpot.head()

,bundleID,soupbase,maindishI,maindishII,dipping,snack,avg_rating
0,1,Tomato Soup Base,Tofu Pudding,Smashed Shrimp Paste,Fragrant,Deep-Fried Crispy Pork,5.47
1,2,Tomato Soup Base,Tofu Pudding,Smashed Shrimp Paste,Fragrant,Dough Stick With Fennel,7.88
2,3,Tomato Soup Base,Tofu Pudding,Smashed Shrimp Paste,Spicy,Deep-Fried Crispy Pork,6.20
3,4,Tomato Soup Base,Tofu Pudding,Smashed Shrimp Paste,Spicy,Dough Stick With Fennel,8.00
4,5,Tomato Soup Base,Tofu Pudding,Smashed Shrimp Paste,Seafood,Deep-Fried Crispy Pork,8.24

In [4]:
hotpot.isnull().values.any()

False

<i> As we can see above that there are no null value in the dataset.

In [10]:
hotpot.describe()

         bundleID  avg_rating
count  384.000000  384.000000
mean   192.500000    6.758594
std    110.995495    1.670385
min      1.000000    1.690000
25%     96.750000    5.570000
50%    192.500000    6.810000
75%    288.250000    7.972500
max    384.000000   10.160000

<i> The describe function gives the descriptive statistics of the variables which summarises the distribution of the variables in the datastet.

In [6]:
hotpot_new = pd.get_dummies(hotpot, drop_first=True, columns=['soupbase', 'maindishI',
'maindishII','dipping','snack'])

<i> The get_dummeis function is used above to convert the categorical value into the dummy values.

In [7]:
hotpot_new.columns

Index(['bundleID', 'avg_rating', 'soupbase_Mushroom Soup Base',
       'soupbase_Three Delicacies Soup Base', 'soupbase_Tomato Soup Base',
       'maindishI_Special Mutton', 'maindishI_Spicy Marinated Beef',
       'maindishI_Tofu Pudding', 'maindishII_Fish Cakes',
       'maindishII_Lobster Tails', 'maindishII_Smashed Shrimp Paste',
       'dipping_Seafood', 'dipping_Spicy', 'snack_Dough Stick With Fennel'],
      dtype='object')

<i> Determining the coefficient values of your model inputs.

In [8]:
X = hotpot_new[['soupbase_Mushroom Soup Base',
       'soupbase_Three Delicacies Soup Base', 'soupbase_Tomato Soup Base',
       'maindishI_Special Mutton', 'maindishI_Spicy Marinated Beef',
       'maindishI_Tofu Pudding', 'maindishII_Fish Cakes',
       'maindishII_Lobster Tails', 'maindishII_Smashed Shrimp Paste',
       'dipping_Seafood', 'dipping_Spicy', 'snack_Dough Stick With Fennel']]

y = hotpot_new['avg_rating']

<i> Building the linear model using the outcome variable Average rating

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics
lmodel  = LinearRegression()
lmodel.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
lmodel.intercept_

6.161718750000002

In [13]:
coef_hotpot = pd.DataFrame(lmodel.coef_,X.columns, columns=['Coefficient'])
coef_hotpot

                                     Coefficient
soupbase_Mushroom Soup Base             0.058750
soupbase_Three Delicacies Soup Base    -0.123229
soupbase_Tomato Soup Base               0.100521
maindishI_Special Mutton                0.805521
maindishI_Spicy Marinated Beef          0.831979
maindishI_Tofu Pudding                  0.223542
maindishII_Fish Cakes                   0.194375
maindishII_Lobster Tails               -0.038438
maindishII_Smashed Shrimp Paste         0.354687
dipping_Seafood                        -0.117344
dipping_Spicy                          -0.119844
snack_Dough Stick With Fennel           0.148021

<i> From the model we can see that Special mutton and the spicy marinated beef has the highest positive coefficient. This infers that the customers like these dish the most and would have a positive effect on the revenue generate. This might be because the carnival attendees prefer spicy food duing the winter season. Also the fact even though maine is famous all over the world for its fresh lobster, the customers prefer meat over the lobster duing winter may be because the reason that the lobster fishing is readuced drastically and the customers are skeptical about the freshness of the lobster. This might be the reason why lobster tail has a negative coefficient. Surprisingly the customers prefer Fish cake and sprimp paste main dish and has a positive coefficient. The spicy dip, seafood dip and the three delicacies soup base has the most negative coefficient. The lobsterland management should focus on including the dishes that have positive coefficient during the memo selection.

In [14]:
hotpot_avg_rating=hotpot.sort_values(by="avg_rating",ascending=False)

In [15]:
hotpot_avg_rating

,bundleID,soupbase,maindishI,maindishII,dipping,snack,avg_rating
221,222,Mushroom Soup Base,Spicy Marinated Beef,Smashed Shrimp Paste,Seafood,Dough Stick With Fennel,10.16
47,48,Tomato Soup Base,Spicy Marinated Beef,Fish Cakes,Seafood,Dough Stick With Fennel,9.97
223,224,Mushroom Soup Base,Spicy Marinated Beef,Crab Sticks,Fragrant,Dough Stick With Fennel,9.96
75,76,Tomato Soup Base,Special Mutton,Smashed Shrimp Paste,Spicy,Dough Stick With Fennel,9.93
40,41,Tomato Soup Base,Spicy Marinated Beef,Lobster Tails,Seafood,Deep-Fried Crispy Pork,9.93
...,...,...,...,...,...,...,...
293,294,Three Delicacies Soup Base,Tofu Pudding,Smashed Shrimp Paste,Seafood,Dough Stick With Fennel,3.24
353,354,Three Delicacies Soup Base,Beef Tripe,Lobster Tails,Seafood,Dough Stick With Fennel,3.20
93,94,Tomato Soup Base,Special Mutton,Fish Cakes,Spicy,Dough Stick With Fennel,3.12
76,77,Tomato Soup Base,Special Mutton,Smashed Shrimp Paste,Seafood,Deep-Fried Crispy Pork,2.63
64,65,Tomato Soup Base,Beef Tripe,Lobster Tails,Seafood,Deep-Fried Crispy Pork,1.69

<i> The average customer rating of the food bundle with Mushroom soup base , spicy marinated beef, smashed srimp paste, seafood dipping and dough stick with fennel snack is highest.

In [28]:
vendor_cost= pd.read_csv('vendor_costs.csv')

In [29]:
vendor_cost

                          Item  Item Category  Cost Per Serving (Dollars)
0             Tomato Soup Base      Soup Base                        3.40
1      Classic Spicy Soup Base      Soup Base                        3.50
2           Mushroom Soup Base      Soup Base                        2.90
3   Three Delicacies Soup Base      Soup Base                        4.60
4                 Tofu Pudding    Main Dish I                        5.70
5         Spicy Marinated Beef    Main Dish I                        6.00
6                   Beef Tripe    Main Dish I                        5.30
7               Special Mutton    Main Dish I                        6.10
8         Smashed Shrimp Paste   Main Dish II                        5.30
9                  Crab Sticks   Main Dish II                        4.70
10               Lobster Tails   Main Dish II                        6.00
11                  Fish Cakes   Main Dish II                        4.70
12                   Fragrant   Dipping Sauce                        0.20
13                      Spicy   Dipping Sauce                        0.10
14                     Seafood  Dipping Sauce                        0.15
15      Deep-Fried Crispy Pork          Snack                        0.60
16     Dough Stick With Fennel          Snack                        0.70

In [30]:
vendor_cost= vendor_cost[['Item','Cost Per Serving (Dollars)' ]]
vendor_cost

                          Item  Cost Per Serving (Dollars)
0             Tomato Soup Base                        3.40
1      Classic Spicy Soup Base                        3.50
2           Mushroom Soup Base                        2.90
3   Three Delicacies Soup Base                        4.60
4                 Tofu Pudding                        5.70
5         Spicy Marinated Beef                        6.00
6                   Beef Tripe                        5.30
7               Special Mutton                        6.10
8         Smashed Shrimp Paste                        5.30
9                  Crab Sticks                        4.70
10               Lobster Tails                        6.00
11                  Fish Cakes                        4.70
12                   Fragrant                         0.20
13                      Spicy                         0.10
14                     Seafood                        0.15
15      Deep-Fried Crispy Pork                        0.60
16     Dough Stick With Fennel                        0.70

In [38]:
all_items=['Tomato Soup Base',
'Classic Spicy Soup Base',
'Mushroom Soup Base',
'Three Delicacies Soup Base',
'Tofu Pudding',
'Spicy Marinated Beef',
'Beef Tripe',
'Special Mutton',
'Smashed Shrimp Paste',
'Crab Sticks',
'Lobster Tails',
'Fish Cakes',
'Fragrant',
'Spicy', 
'Seafood',
'Deep Fried Crispy Pork',
'Dough Stick with Fennel']

all_cost=[3.40 ,3.50 ,2.90 ,4.60 ,5.70 ,6.00 ,5.30 ,6.10 ,5.30 ,4.70 ,6.00 ,4.70 ,0.20 ,0.10 ,0.15 ,0.60 ,0.70]

In [39]:
df2 = pd.DataFrame({'all_items':all_items, 'all_cost':all_cost})

In [40]:
bundle_222= ['Mushroom Soup Base','Spicy Marinated Beef', 'Smashed Shrimp Paste','Seafood','Dough Stick with Fennel']
bundle_48=['Tomato Soup Base','Spicy Marinated Beef','Fish Cakes','Seafood','Dough Stick with Fennel']
bundle_223=['Mushroom Soup Base','Spicy Marinated Beef','Crab Sticks','Fragrant','Dough Stick with Fennel']
bundle_75=['Tomato Soup Base','Special Mutton','Smashed Shrimp Paste','Spicy','Dough Stick with Fennel']

In [41]:
df1 = pd.DataFrame({'bundle_222':bundle_222, 'bundle_48':bundle_48, 'bundle_223':bundle_223, 'bundle_75':bundle_75})

In [43]:
rename_dict = df2.set_index('all_items').to_dict()['all_cost']

In [44]:
df1 = df1.replace(rename_dict)
df1

   bundle_222  bundle_48  bundle_223  bundle_75
0        2.90       3.40         2.9        3.4
1        6.00       6.00         6.0        6.1
2        5.30       4.70         4.7        5.3
3        0.15       0.15         0.2        0.1
4        0.70       0.70         0.7        0.7

In [45]:
df1.sum()

bundle_222    15.05
bundle_48     14.95
bundle_223    14.50
bundle_75     15.60
dtype: float64

<i> Since the price of the hotpot is set as standard 15 dollars for all the customers, the bundel with Tomato Soup Base, Spicy Marinated Beef , Fish Cakes,Seafood and Dough Stick With Fenne costs under 15 dollars. The Lobsterland management should consider this memo selection in order to provide the customer of the hotpot a very satisfying experience and to create an opportunity to generate higher revenue from the Hotpot.

## One Page Memo

<i> Soup: Tomato Soup Base

Main Dish 1: Spicy Marinated Beef

Main Dish 2: Fish Cake

Dip: Seafood

Snack: Dough Stick With Fennel